#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : winpdb
Version  : 1.5.0
Release  : 1
URL      : https://github.com/bluebird75/winpdb/archive/WINPDB_1_5_0.tar.gz
Source0  : https://github.com/bluebird75/winpdb/archive/WINPDB_1_5_0.tar.gz
Summary  : No detailed summary available
Group    : Development/Tools
License  : GPL-2.0
Requires: winpdb-bin
Requires: winpdb-python3
Requires: winpdb-license
Requires: winpdb-python
BuildRequires : buildreq-distutils3

%description
|Build Status Linux| |Build status Windows|
*Winpdb Reborn - A GPL Python Debugger, reborn from the unmaintained
Winpdb*

%package bin
Summary: bin components for the winpdb package.
Group: Binaries
Requires: winpdb-license

%description bin
bin components for the winpdb package.


%package license
Summary: license components for the winpdb package.
Group: Default

%description license
license components for the winpdb package.


%package python
Summary: python components for the winpdb package.
Group: Default
Requires: winpdb-python3

%description python
python components for the winpdb package.


%package python3
Summary: python3 components for the winpdb package.
Group: Default
Requires: python3-core

%description python3
python3 components for the winpdb package.


%prep
%setup -q -n winpdb-WINPDB_1_5_0

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C
export SOURCE_DATE_EPOCH=1535859294
python3 setup.py build -b py3

%install
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/doc/winpdb
cp LICENSE.txt %{buildroot}/usr/share/doc/winpdb/LICENSE.txt
python3 -tt setup.py build -b py3 install --root=%{buildroot}
echo ----[ mark ]----
cat %{buildroot}/usr/lib/python3*/site-packages/*/requires.txt || :
echo ----[ mark ]----

%files
%defattr(-,root,root,-)

%files bin
%defattr(-,root,root,-)
/usr/bin/rpdb2
/usr/bin/winpdb

%files license
%defattr(-,root,root,-)
/usr/share/doc/winpdb/LICENSE.txt

%files python
%defattr(-,root,root,-)

%files python3
%defattr(-,root,root,-)
/usr/lib/python3*/*
